# Generated by Django 2.0 on 2020-05-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_statut', models.CharField(choices=[('1', '1 pers'), ('2', '2 pers'), ('3', '3 pers'), ('4', '4 pers'), ('5', '5 pers'), ('6', '6 pers'), ('7', '7 pers'), ('8', '8 pers'), ('9', '9 pers')], default='1', max_length=16, verbose_name='Nombre de personne foyer')),
                ('a_type', models.CharField(choices=[('1', '1 portion'), ('2', '2 portions'), ('3', '3 portions'), ('4', '4 portions'), ('5', '5 portions'), ('6', '6 portions'), ('7', '7 portions'), ('8', '8 portions'), ('9', '9 portion')], default='1', max_length=16, verbose_name='Portion de riz souhaitée')),
                ('a_type2', models.CharField(choices=[('1', '1 portion'), ('2', '2 portions'), ('3', '3 portions'), ('4', '4 portions'), ('5', '5 portions'), ('6', '6 portions'), ('7', '7 portions'), ('8', '8 portions'), ('9', '9 portion')], default='1', max_length=16, verbose_name='Portion de pates souhaitée')),
                ('a_type3', models.CharField(choices=[('1', '1 portion'), ('2', '2 portions'), ('3', '3 portions'), ('4', '4 portions'), ('5', '5 portions'), ('6', '6 portions'), ('7', '7 portions'), ('8', '8 portions'), ('9', '9 portion')], default='1', max_length=16, verbose_name='Portion de viande souhaitée')),
                ('a_description', models.TextField(verbose_name='un produit à suggérer')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=128, verbose_name='Nom du foyer')),
                ('c_nbPersonnes', models.IntegerField(verbose_name='Nombre de personnes')),
                ('c_nomsPersonnes', models.CharField(max_length=128, verbose_name='Noms des personnes')),
                ('c_email', models.EmailField(max_length=254, verbose_name='Votre email')),
                ('c_mdp', models.CharField(max_length=128, verbose_name='Tapez votre mot de passe')),
                ('c_numTel', models.CharField(max_length=128, verbose_name='Numéro de téléphone')),
                ('c_adresse', models.CharField(max_length=128, verbose_name='Adresse')),
                ('c_codepostal', models.CharField(max_length=128, verbose_name='Code postal')),
                ('c_ville', models.CharField(max_length=128, verbose_name='Ville')),
                ('c_pays', models.CharField(max_length=128, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_titre', models.CharField(max_length=128, unique=True, verbose_name='Titre')),
                ('p_titre_slugify', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Titre Slugify')),
                ('p_adresse', models.CharField(max_length=64, verbose_name='Adresse')),
                ('p_mots_clefs', models.CharField(blank=True, max_length=512, verbose_name='Mots clés')),
                ('p_description', models.TextField(verbose_name='Description')),
                ('p_contenu', models.TextField(verbose_name='Contenu')),
                ('p_bouillon', models.BooleanField(default=True, verbose_name='Bouillon')),
            ],
            options={
                'verbose_name': 'Gestion des pages',
                'verbose_name_plural': 'Gestion des pages',
                'ordering': ['p_adresse'],
            },
        ),
    ]
